Jenkinsfile updated

diff --git a/run-smoke-tests b/run-smoke-tests
--- a/run-smoke-tests
+++ b/run-smoke-tests
@@ -1,2 +1,2 @@
 #!/bin/bash
-echo "Smoke tests succeeded"; exit 0
+echo "Smoke tests Failed!"; exit 1
